version: '3'
services:
  web:
    build: .
    volumes:
     - .:/go/src/app
    ports:
     - "8080:8080"
    depends_on:
     - db
  db:
    image: postgres:latest
    volumes:
     - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
